### ISSUE TITLE
hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [stevecondylios/dictionaRy#4]
Hello, 
I saw your r4ds slack post about logos. 
Just posting initial reply and will post a mockup tomorrow.

**Comment by PythonCoderUnicorn** [comment]
Hello,
I made some mockups based on how the Oxford English dictionary looks, hope you like one of these and if not things can be changed.  

also, thanks for making this package, very cool. 

<img width="517" alt="Screen Shot 2022-01-05 at 12 39 59 PM" src="https://user-images.githubusercontent.com/55933131/148278522-6e33f6b9-71f5-4560-89db-a54517a613ec.png">


If you do like it, please tag me as Zane Dax (She/They) @StarTrek_Lt

**Comment by PythonCoderUnicorn** [comment]
design 4
![dictionary logo 4](https://user-images.githubusercontent.com/55933131/148304966-14db0a98-ba21-4b72-854a-e8f4426a4981.png)

design 6
![dictionary logo 6](https://user-images.githubusercontent.com/55933131/148305007-4b8cb659-6b28-467a-b4b4-67c25a85327e.png)

**Comment by stevecondylios** [comment]
Thanks so much @PythonCoderUnicorn , these are fantastic!

**Comment by stevecondylios** [comment]
[README.md](https://github.com/stevecondylios/dictionary#dictionary-) (and [`DESCRIPTION`](https://github.com/stevecondylios/dictionary/blob/master/DESCRIPTION)) updated! 

Thanks again for this great contribution!
